//
// Copyright (c) 2010-2026 Antmicro
//
// This file is licensed under the MIT License.
// Full license text is available in 'licenses/MIT.txt'.
//

using System;
using System.Security.Cryptography;

namespace Antmicro.Renode.Peripherals.Wireless
{
    public class Em9305LinkLayer : IDisposable
    {
        private static readonly byte[] AdvertisingAccessAddress = { 0xD6, 0xBE, 0x89, 0x8E };

        private const int AdvDirectIndOpCode = 0x02;
        private const int ConnectIndOpCode = 0x08;
        private const int TxAddBit = 1 << 4;
        private const int RxAddBit = 1 << 5;

        // Data-channel (connection) LL control opcodes, carried in the low nibble of header byte.
        private const int StartEncReqType = 0x0A;   // master -> slave: carries connAA + random E (unencrypted)
        private const int StartEncRspType = 0x0B;   // slave -> master: handshake complete (unencrypted)
        private const int DataPduType     = 0x06;   // LL_DATA payload
        private const int PairPubOp       = 0x0C;   // SMP/LESC: carries own ephemeral pub key X||Y + 128-bit random (unencrypted)

        // SMP / LE Secure Connections protocol opcodes (real legacy SLC link-layer PDU numbers), carried on the
        // data channel after connection. These make pairing a visible request/response procedure rather than just
        // a local LKDH: exchange of capabilities, an over-the-air f4 DHKey-check, and Encrypted-Info LTK distribution.
        private const int PairingReqOp    = 0x18;   // initiator -> responder: [ioCap][oob][authReq][keKLen] + ownRandom(16), unencrypted
        private const int PairingRspOp    = 0x19;   // responder -> initiator: same params block + ownRandom(16), unencrypted
        private const int DhCheckOp       = 0x22;   // initiator -> responder: f4 DHKey-check confirm value (16 bytes), unencrypted
        private const int LtkInfoOp       = 0x3B;   // Encrypted Info: [LTK(16)][EDIV(2)][Rand(8)], encrypted with the derived LTK

        private const byte EncBit         = 0x10;   // header bit 4: payload is encrypted

        private readonly AmbiqEM9305Radio radio;
        private bool disposed;

        public byte[] OwnAddress { get; set; } = new byte[6];
        public byte[] PeerAddress { get; set; } = new byte[6];
        public ushort EndOfAnchoringPoint { get; set; } = 0x0080;
        public ushort ConnectEventLength { get; set; } = 0x0034;

        public bool Connected { get; private set; }
        public event Action<Em9305LinkLayer> ConnectionEstablished;

        // ---- Link-layer (data channel) encryption state ----
        public byte[] LastDecryptedPayload { get; private set; } = Array.Empty<byte>();
        public bool Encrypted { get; private set; }
        public event Action<Em9305LinkLayer, byte[]> DataReceived;

        private readonly byte[] connAccessAddress = new byte[4];
        private byte[] ltk = new byte[16];
        private ulong randomE;      // 64-bit random E generated by the master (fixed per link)
        private ulong txCounter;    // increments per encrypted PDU this node transmits
        private ulong rxCounter;    // increments per encrypted PDU this node receives

        // ---- LE Secure Connections pairing (ephemeral ECDH on P-256 -> f5 LKDH) ----
        private byte[] ephPriv, ephPubX, ephPubY, ownRandom;              // own ephemeral material (generated once per pairing)
        private byte[] peerEphPubX = new byte[32], peerEphPubY = new byte[32];  // peer's published public key
        private byte[] peerRandom = new byte[16];                            // peer's 128-bit random
        private bool gotPeerPub;                                            // peer's Pair PDU has been seen
        private bool isInitiator;                                           // true on the side that also drives START_ENC

        public byte[] PairedLtk { get; private set; }                       // LTK derived by f5 (identical on both peers)
        public byte[] PairedMacKey { get; private set; }                    // MAC key from f5 (reserved for MIC checking)
        public byte[] PairedDhKey { get; private set; }                     // shared P-256 DH secret g1(ephA, ephB), identical on both peers
        public bool PairingComplete { get; private set; }

        // ---- SMP / LE Secure Connections pairing-procedure state & observability ----
        public bool SmpComplete { get; private set; }             // full procedure done: LKDH + DHKey check + LTK distribution

        public byte IoCapability  { get; set; } = 0x03;           // NoInputNoOutput (Just-Works-capable)
        public bool ScCapable     { get; set; } = true;          // LE Secure Connections supported (AuthReq bit 3)
        public bool MitmRequested { get; set; }                  // MITM protection requested (AuthReq bit 1)
        public byte KekLength     { get; set; } = 0x07;          // LTK length in octets: 7 or 16

        public bool PairingRequestReceived    { get; private set; }
        public bool PairingResponseReceived   { get; private set; }
        public byte[] EphemeralPubX           => ephPubX;        // expose own pub key X for the f4 oracle / harness
        public bool DhKeyCheckPassed          { get; private set; }  // responder verified the initiator's f4 confirm value

        public byte[] BondedLtk               { get; private set; }  // peer LTK received via Encrypted Info (bonding)
        public bool   LtkDistributed          { get; private set; }  // Encrypted-Info PDU was received and decrypted
        public bool   BondLtkMatchesOwn       { get; private set; }  // received bond LTK == our own f5-derived LTK

        public Em9305LinkLayer(AmbiqEM9305Radio radio)
        {
            this.radio = radio;
            radio.FrameReceived += OnFrameReceived;
        }

        public void StartDirectedAdvertising()
        {
            Transmit(BuildAdvDirectInd(OwnAddress, PeerAddress));
        }

        private byte[] BuildAdvDirectInd(byte[] advA, byte[] peerA)
        {
            var pdu = new byte[4 + 1 + 6 + 6];
            Array.Copy(AdvertisingAccessAddress, 0, pdu, 0, 4);
            pdu[4] = (byte)(AdvDirectIndOpCode | TxAddBit);
            Array.Copy(advA, 0, pdu, 5, 6);
            Array.Copy(peerA, 0, pdu, 11, 6);
            return pdu;
        }

        private byte[] BuildConnectInd(byte[] advA, byte[] peerA)
        {
            var pdu = new byte[4 + 1 + 6 + 6 + 2 + 2];
            Array.Copy(AdvertisingAccessAddress, 0, pdu, 0, 4);
            pdu[4] = (byte)(ConnectIndOpCode | TxAddBit | RxAddBit);
            Array.Copy(advA, 0, pdu, 5, 6);
            Array.Copy(peerA, 0, pdu, 11, 6);
            pdu[17] = (byte)(EndOfAnchoringPoint & 0xFF);
            pdu[18] = (byte)((EndOfAnchoringPoint >> 8) & 0xFF);
            pdu[19] = (byte)(ConnectEventLength & 0xFF);
            pdu[20] = (byte)((ConnectEventLength >> 8) & 0xFF);
            return pdu;
        }

        private void OnFrameReceived(byte[] frame, IRadio sender)
        {
            if(frame == null || frame.Length < 6)
            {
                return;
            }

            if(!MatchesAccessAddress(frame))
            {
                // Not on the advertising access address: treat as a data-channel (connection) PDU.
                HandleDataChannelPdu(frame);
                return;
            }

            var opCode = frame[4] & 0x0F;
            var txAdd = (frame[4] & TxAddBit) != 0;
            var rxAdd = (frame[4] & RxAddBit) != 0;

            if(opCode == AdvDirectIndOpCode && txAdd && frame.Length >= 17)
            {
                var advA = CopyRange(frame, 5, 6);
                var peerA = CopyRange(frame, 11, 6);
                if(AddressesEqual(peerA, OwnAddress))
                {
                    Connected = true;
                    Transmit(BuildConnectInd(advA, OwnAddress));
                    ConnectionEstablished?.Invoke(this);
                }
            }
            else if(opCode == ConnectIndOpCode && txAdd && rxAdd && frame.Length >= 21)
            {
                var advA = CopyRange(frame, 5, 6);
                if(AddressesEqual(advA, OwnAddress))
                {
                    Connected = true;
                    ConnectionEstablished?.Invoke(this);
                }
            }
        }

        private static bool MatchesAccessAddress(byte[] frame)
        {
            for(var i = 0; i < AdvertisingAccessAddress.Length; i++)
            {
                if(frame[i] != AdvertisingAccessAddress[i])
                {
                    return false;
                }
            }
            return true;
        }

        private static byte[] CopyRange(byte[] src, int offset, int count)
        {
            var dst = new byte[count];
            Array.Copy(src, offset, dst, 0, count);
            return dst;
        }

        private static bool AddressesEqual(byte[] a, byte[] b)
        {
            if(a == null || b == null || a.Length != 6 || b.Length != 6)
            {
                return false;
            }
            for(var i = 0; i < 6; i++)
            {
                if(a[i] != b[i])
                {
                    return false;
                }
            }
            return true;
        }

        private void Transmit(byte[] pdu)
        {
            radio.TransmitFrame(pdu);
        }

        // The controller supplies the long-term key once known (from pairing, or set directly in tests).
        public void ConfigureEncryption(byte[] ltk)
        {
            if(ltk == null || ltk.Length != 16)
            {
                throw new ArgumentException("LTK must be exactly 16 bytes", nameof(ltk));
            }

            this.ltk = (byte[])ltk.Clone();
        }

        // Master side: begin the START_ENC exchange. The connection access address and the 64-bit random E
        // are carried on an unencrypted control PDU so the slave can learn both; afterwards every Data PDU
        // is encrypted with AES-128 CTR over (LTK, E, per-direction counter).
        public void InitiateStartEnc(ulong randomE)
        {
            if(!Connected)
            {
                return;
            }

            this.randomE = randomE;
            var aa = DeriveConnectionAccessAddress();
            Array.Copy(aa, 0, connAccessAddress, 0, 4);

            var payload = new byte[12];        // [E:8 LE][counter(=0):4] - counter field stays zero at start
            WriteLE64(payload, 0, randomE);
            Transmit(BuildDataChannelPdu(connAccessAddress, false, StartEncReqType, payload));

            txCounter = 0;
            rxCounter = 0;
        }

        // Host -> link layer: transmit an encrypted Data PDU. Returns false if the link is not yet encrypted.
        public bool SendEncryptedData(byte[] payload)
        {
            if(!Encrypted || payload == null)
            {
                return false;
            }

            var enc = (byte[])payload.Clone();
            ApplyCtr(enc, 0, enc.Length, txCounter++);
            Transmit(BuildDataChannelPdu(connAccessAddress, true, DataPduType, enc));
            return true;
        }

        // Begin LE Secure Connections pairing over the established data channel. The device that will drive
        // START_ENC should pass initiator=true so both sides order the f5 inputs identically. If no fixed
        // ephemeral key / random are supplied, fresh P-256 + 128-bit values are generated (inject them for
        // deterministic tests). Once both sides have exchanged public keys, an LTK is derived via f5 and the
        // link layer is left ready to run START_ENC + encrypted Data PDUs with no manual key injection.
        public void StartSecureConnections(bool initiator, byte[] fixedEphemeralPriv = null, byte[] fixedOwnRandom = null)
        {
            if(!Connected)
            {
                return;
            }

            isInitiator = initiator;
            EnsureOwnEphemeral(fixedEphemeralPriv, fixedOwnRandom);

            // [Qx:32][Qy:32][random:16] on an unencrypted data-channel control PDU.
            Transmit(BuildDataChannelPdu(DeriveConnectionAccessAddress(), false, PairPubOp, BuildPairPubPayload()));

            TryCompletePairing();   // peer's public key may already have arrived before ours was generated
        }

        // Generate (or reuse) our ephemeral P-256 private key, public point and 128-bit pairing random. Fixed values are
        // honoured for deterministic tests; otherwise cryptographically-random material is produced exactly once per pairing.
        private void EnsureOwnEphemeral(byte[] fixedPriv, byte[] fixedRandom)
        {
            if(ephPriv == null)
            {
                var useFixedPriv = fixedPriv != null && fixedPriv.Length == 32;
                ephPriv = useFixedPriv ? (byte[])fixedPriv.Clone() : new byte[32];
                if(!useFixedPriv)
                {
                    RandomNumberGenerator.Fill(ephPriv);
                }

                var pub = BleScCrypto.GeneratePublicKey(ephPriv);   // Q = priv * G
                ephPubX = pub.X;
                ephPubY = pub.Y;
            }

            if(ownRandom == null || ownRandom.Length != 16)
            {
                var useFixedRandom = fixedRandom != null && fixedRandom.Length == 16;
                ownRandom = useFixedRandom ? (byte[])fixedRandom.Clone() : new byte[16];
                if(!useFixedRandom)
                {
                    RandomNumberGenerator.Fill(ownRandom);
                }
            }
        }

        private byte[] BuildPairPubPayload()
        {
            var payload = new byte[80];   // [Qx:32][Qy:32][random:16]
            Array.Copy(ephPubX, 0, payload, 0, 32);
            Array.Copy(ephPubY, 0, payload, 32, 32);
            Array.Copy(ownRandom, 0, payload, 64, 16);
            return payload;
        }

        // Arm one side for an SMP/LESEC pairing run without transmitting anything. Call on BOTH sides before the
        // initiator calls BeginSmpPairing() so the responder is ready to answer the request. Fixed values (optional)
        // are honoured for deterministic tests, mirroring StartSecureConnections().
        public void PrepSecureConnections(bool initiator, byte[] fixedEphemeralPriv = null, byte[] fixedOwnRandom = null)
        {
            if(!Connected)
            {
                return;
            }

            isInitiator = initiator;
            EnsureOwnEphemeral(fixedEphemeralPriv, fixedOwnRandom);
        }

        // Initiator-only: drive the whole SMP/LESEC pairing procedure over the air. Requires PrepSecureConnections() on
        // both sides first (the responder must be armed to answer). Over a shared BLEMedium with SynchronizedTimers this
        // cascades synchronously in a single call:
        //   PairingReq -> (responder) PairingRsp + its PairPub ; initiator then sends its own PairPub, the f4 DHKey-check
        //   confirm value, and finally distributes its LTK via an Encrypted-Info PDU. The responder verifies the check and
        //   stores the received bond LTK as each step lands.
        public void BeginSmpPairing()
        {
            if(!Connected || !isInitiator)
            {
                return;
            }

            EnsureOwnEphemeral(null, null);
            var aa = DeriveConnectionAccessAddress();

            // 1) Pairing Request: [ioCap][oob=0][authReq][keKLen] + ownRandom(16). Responder answers synchronously.
            Transmit(BuildDataChannelPdu(aa, false, PairingReqOp, ConcatBytes(BuildPairingParams(), ownRandom)));

            // 2) Publish our ephemeral public key (responder already sent its own when it handled the request above).
            Transmit(BuildDataChannelPdu(aa, false, PairPubOp, BuildPairPubPayload()));

            TryCompletePairing();   // f5 LKDH once both pub keys are known -> PairedLtk/MacKey/DhKey set on this side

            if(!PairingComplete)
            {
                return;
            }

            // 3) f4 DHKey-check confirm value, carried over the air so the responder can verify integrity of the key exchange.
            var confirm = BleScCrypto.F4(ephPubX, peerEphPubX, 0x01, F4Key());
            Transmit(BuildDataChannelPdu(aa, false, DhCheckOp, confirm));

            // 4) Distribute our LTK for bonding via an Encrypted-Info PDU (encrypted with the derived LTK).
            SendEncryptedLtkInfo(aa);

            SmpComplete = true;   // initiator finished: request/response + pub keys + f5 LKDH + DHKey check + LTK distribution
        }

        private byte[] BuildPairingParams()
        {
            var authReq = (byte)((MitmRequested ? 0b10 : 0) | (ScCapable ? 0b10000 : 0));   // bit1=MITM, bit3=SC
            return new byte[] { IoCapability, 0x00 /* oob = No OOB data */, authReq, KekLength };
        }

        private void SendEncryptedLtkInfo(byte[] aa)
        {
            if(PairedLtk == null || PairedLtk.Length != 16)
            {
                return;
            }

            var pt = new byte[26];   // [LTK:16][EDIV:2=0x0001][Rand:8]
            Array.Copy(PairedLtk, 0, pt, 0, 16);
            pt[16] = 0x01;
            var rand = new byte[] { 0xA5, 0x10, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10 };
            Array.Copy(rand, 0, pt, 18, 8);

            var ct = (byte[])pt.Clone();
            ApplyCtr(ct, 0, ct.Length, 0);   // counter base 0; distinct from the post-START_ENC data counters
            Transmit(BuildDataChannelPdu(aa, true, LtkInfoOp, ct));
        }

        private void HandlePairingRequest(byte[] frame)
        {
            if(frame.Length < 6 + 4 + 16)
            {
                return;
            }

            IoCapability = frame[6];   // learn peer's IO capability (informational on the responder)
            Array.Copy(frame, 6 + 4, peerRandom, 0, 16);   // initiator's random carried in its request
            PairingRequestReceived = true;

            EnsureOwnEphemeral(null, null);
            var aa = DeriveConnectionAccessAddress();
            // Answer with our own params + random, and publish our public key so the initiator can finish f5.
            Transmit(BuildDataChannelPdu(aa, false, PairingRspOp, ConcatBytes(BuildPairingParams(), ownRandom)));
            Transmit(BuildDataChannelPdu(aa, false, PairPubOp, BuildPairPubPayload()));
        }

        private void HandlePairingResponse(byte[] frame)
        {
            if(frame.Length < 6 + 4 + 16)
            {
                return;
            }

            Array.Copy(frame, 6 + 4, peerRandom, 0, 16);   // responder's random carried in its response
            PairingResponseReceived = true;
        }

        private void HandleDhKeyCheck(byte[] frame)
        {
            if(frame.Length < 6 + 16 || ephPubX == null || peerEphPubX == null)
            {
                return;
            }

            var got = CopyRange(frame, 6, 16);
            // Responder's view: U = peer(initiator) pub X, V = own pub X, Z = initiatorRandom||responderRandom.
            var expect = BleScCrypto.F4(peerEphPubX, ephPubX, 0x01, F4Key());   // same symmetric key as the initiator's confirm
            DhKeyCheckPassed = SequenceEqualLocal(got, expect);
        }

        // Symmetric 128-bit CMAC key for the f4 DHKey-check: XOR of the two pairing nonces. Both peers hold both
        // nonces, and XOR is commutative, so initiator and responder derive the identical 16-byte Z (f4's AES-CMAC key).
        private byte[] F4Key()
        {
            var k = new byte[16];
            for(var i = 0; i < 16; i++)
            {
                k[i] = (byte)(ownRandom[i] ^ peerRandom[i]);
            }

            return k;
        }

        private static byte[] ConcatBytes(params byte[][] parts)
        {
            var total = 0;
            foreach(var p in parts)
            {
                total += p.Length;
            }

            var outp = new byte[total];
            var off = 0;
            foreach(var p in parts)
            {
                Array.Copy(p, 0, outp, off, p.Length);
                off += p.Length;
            }

            return outp;
        }

        private static bool SequenceEqualLocal(byte[] a, byte[] b)
        {
            if(a == null || b == null || a.Length != b.Length)
            {
                return false;
            }

            for(var i = 0; i < a.Length; i++)
            {
                if(a[i] != b[i])
                {
                    return false;
                }
            }

            return true;
        }

        private void HandlePairPub(byte[] frame)
        {
            if(frame.Length < 6 + 80)
            {
                return;
            }

            Array.Copy(frame, 6, peerEphPubX, 0, 32);
            Array.Copy(frame, 38, peerEphPubY, 0, 32);
            Array.Copy(frame, 70, peerRandom, 0, 16);
            gotPeerPub = true;
            TryCompletePairing();
        }

        private void TryCompletePairing()
        {
            if(PairingComplete || !Connected || ephPriv == null || !gotPeerPub)
            {
                return;
            }

            // Shared P-256 DH secret = G1(own_priv, peer_pub): identical on both peers.
            var dhKey = BleScCrypto.G1(ephPriv, peerEphPubX, peerEphPubY);

            // f5 inputs must be ordered identically on both sides: Na=initiator random, Nb=responder random;
            // aI/aR are the initiator's / responder's [addrType + address] blocks. "own" and "peer" swap by
            // role, but resolving against isInitiator makes na/nb/aiBlock/arBlock the same bytes on both ends.
            byte[] na = isInitiator ? ownRandom : peerRandom;      // the INITIATOR's 128-bit random
            byte[] nb = isInitiator ? peerRandom : ownRandom;      // the RESPONDER's 128-bit random
            var initAddr = isInitiator ? OwnAddress : PeerAddress; // initiator's address (same on both sides)
            var respAddr = isInitiator ? PeerAddress : OwnAddress; // responder's address (same on both sides)

            var aiBlock = BuildF5AddrBlock(0x00, initAddr);        // fixed type byte for the initiator role
            var arBlock = BuildF5AddrBlock(0x01, respAddr);        // fixed type byte for the responder role

            var f5 = BleScCrypto.F5(dhKey, na, nb, aiBlock, arBlock);
            PairedDhKey = (byte[])dhKey.Clone();
            PairedLtk = (byte[])f5.Ltk.Clone();
            PairedMacKey = (byte[])f5.MacKey.Clone();
            ConfigureEncryption(f5.Ltk);                          // ready for START_ENC + encrypted Data PDUs
            PairingComplete = true;
        }

        private static byte[] BuildF5AddrBlock(byte type, byte[] addr)
        {
            var b = new byte[7];   // [addrType:1][address:6] per the BLE SC spec (aI / aR inputs to f5)
            b[0] = type;
            if(addr != null)
            {
                Array.Copy(addr, 0, b, 1, Math.Min(6, addr.Length));
            }

            return b;
        }

        private void HandleDataChannelPdu(byte[] frame)
        {
            var type = frame[5];                             // opcode carried in its own byte (see BuildDataChannelPdu)
            var enc = (frame[4] & EncBit) != 0;
            Array.Copy(frame, 0, connAccessAddress, 0, 4);   // learn/confirm the connection access address

            if(type == StartEncReqType)
            {
                randomE = ReadLE64(frame, 6);                 // [E:8] at payload offset 0 (frame index 6)
                txCounter = 0;
                rxCounter = 0;
                Encrypted = true;
                Transmit(BuildDataChannelPdu(connAccessAddress, false, StartEncRspType, Array.Empty<byte>()));
            }
            else if(type == StartEncRspType)
            {
                txCounter = 0;                                // master side: handshake complete
                rxCounter = 0;
                Encrypted = true;
            }
            else if(type == PairPubOp)
            {
                HandlePairPub(frame);                         // SMP/LESC public-key exchange (unencrypted control PDU)
            }
            else if(type == PairingReqOp)
            {
                HandlePairingRequest(frame);                  // SMP/LESEC pairing request from the initiator
            }
            else if(type == PairingRspOp)
            {
                HandlePairingResponse(frame);                 // SMP/LESEC pairing response from the responder
            }
            else if(type == DhCheckOp)
            {
                HandleDhKeyCheck(frame);                      // f4 DHKey-check confirm value verification (responder side)
            }
            else if(type == LtkInfoOp && enc)
            {
                var plen = frame.Length - 6;                  // Encrypted Info: [LTK(16)][EDIV(2)][Rand(8)]
                var buf = new byte[plen];
                Array.Copy(frame, 6, buf, 0, plen);
                ApplyCtr(buf, 0, buf.Length, 0);              // same counter base as the sender (pre-START_ENC)
                BondedLtk = CopyRange(buf, 0, 16);
                LtkDistributed = true;
                BondLtkMatchesOwn = PairedLtk != null && SequenceEqualLocal(BondedLtk, PairedLtk);
                if(PairingComplete && DhKeyCheckPassed)
                {
                    SmpComplete = true;                       // full SMP procedure finished on this side
                }
            }
            else if(type == DataPduType && enc)
            {
                var plen = frame.Length - 6;
                var plain = new byte[plen];
                Array.Copy(frame, 6, plain, 0, plen);
                ApplyCtr(plain, 0, plen, rxCounter++);        // CTR is symmetric: decrypt == keystream XOR
                LastDecryptedPayload = plain;
                DataReceived?.Invoke(this, plain);
            }
        }

        private byte[] BuildDataChannelPdu(byte[] aa, bool enc, int type, byte[] payload)
        {
            var plen = payload == null ? 0 : payload.Length;
            var pdu = new byte[6 + plen];
            Array.Copy(aa, 0, pdu, 0, 4);                     // connection access address (data channel)
            pdu[4] = (byte)(enc ? EncBit : 0);                // header low: bit4 = encrypted flag only
            pdu[5] = (byte)type;                              // opcode in its own byte (values exceed a nibble, e.g. PairingReqOp=0x18)
            if(plen > 0)
            {
                Array.Copy(payload, 0, pdu, 6, plen);
            }

            return pdu;
        }

        private byte[] DeriveConnectionAccessAddress()
        {
            var aa = new byte[4];
            for(var i = 0; i < 4; i++)
            {
                aa[i] = (byte)(OwnAddress[i] ^ 0x5A);         // deterministic per master; slave learns the real AA from the frame
            }

            return aa;
        }

        // XOR buf[offset..offset+len) with an AES-128 CTR keystream. The 128-bit counter block is
        // [E (low 64 bits, fixed per link)] || [counter+blockIndex (high 64 bits)], both little-endian.
        private void ApplyCtr(byte[] buf, int offset, int len, ulong baseCounter)
        {
            if(len == 0)
            {
                return;
            }

            var blockIn = new byte[16];
            WriteLE64(blockIn, 0, randomE);                   // low half: E (constant for this link)
            var nblocks = (len + 15) / 16;
            for(var b = 0; b < nblocks; b++)
            {
                WriteLE64(blockIn, 8, baseCounter + (ulong)b); // high half: counter (+ intra-payload block index)
                var ks = BleScCrypto.AesEcbBlock(ltk, blockIn);
                var start = offset + b * 16;
                for(var j = 0; j < 16 && (start + j) < offset + len; j++)
                {
                    buf[start + j] = (byte)(buf[start + j] ^ ks[j]);
                }
            }
        }

        private static void WriteLE64(byte[] buf, int offset, ulong value)
        {
            for(var i = 0; i < 8; i++)
            {
                buf[offset + i] = (byte)(value >> (8 * i));
            }
        }

        private static ulong ReadLE64(byte[] buf, int offset)
        {
            ulong v = 0;
            for(var i = 7; i >= 0; i--)
            {
                v |= (ulong)buf[offset + i] << (8 * i);
            }

            return v;
        }

        public void Dispose()
        {
            if(!disposed)
            {
                disposed = true;
                radio.FrameReceived -= OnFrameReceived;
            }
        }
    }
}
